### PR TITLE
Add collections

### PR DESCRIPTION
**Pull request by glenrobson**
Trying with renamed branch with out _ in the name...

### CODE REVIEW

**Comment by glenrobson** [comment]
Example collection: https://gist.github.com/glenrobson/f93330bac2efc7e4103caa7dc8e61c92

This fixes:

 * add types for collection and manifests.
 * Re-order so its label at the top.
 * Add description as summary.

**Comment by benwbrum** [comment]
This looks good; description, ordering, and types are all great.

The only thing I'd add to the wish-list for future work would be to multi-lingualize the "Page 3 of 8" label.  Since we're generating that text, we know it's English so don't need to use `none` for the language, plus we can add translations to other languages.

**Comment by hadro** [comment]
Maybe worth adding a new issue for wishlist items like that, given that
we’re quickly approaching the basics for 1.0 release?

**Comment by glenrobson** [comment]
For the short term I've set the label of the next collection as English:

```
{
      "id": "http://localhost:8080/iiif/3/frankbford/2/collection.json",
      "label": {
        "en": [
          "Page 2 of 8"
        ]
      },
      "type": "Collection"
}
```

**Pull request merged**
