### PR TITLE
Add logic for etree and 24bit flac

### PR DESCRIPTION
**Pull request by hadro**

### CODE REVIEW

**Comment by hadro** [comment]
Draft PR to add in logic to (hopefully) fix #123

**Comment by hadro** [comment]
@digitaldogsbody, if you get a chance, would love a gut-check on whether I'm competently adjusted the logic in the resolver to account for some of the file types I encountered when trying to get some of the Live Music Archive stuff on IA working with our setup. 

This adds a few filetypes, but there's still the open question in #125 about whether we want to be comprehensive or not.

**Comment by digitaldogsbody** [comment]
Changes look good to me :)

**Review by digitaldogsbody — APPROVED** [review]

**Comment by glenrobson** [comment]
Could we add a test?

**Pull request merged**
